[DEFAULT]
AccessType = OnPremise
SignOfLifeLog = 1

[ONPREMISE]
Host=192.168.1.99:7070

[LOADPOINT0]
Deviceinstance = 43
Name = Wallbox 1
# Position: 0 = AC-Out, 1 = AC-In 1, 2 = AC-In 2
Position = 1

[LOADPOINT1]
Deviceinstance = 44
Name = Wallbox 2
# Position: 0 = AC-Out, 1 = AC-In 1, 2 = AC-In 2
Position = 1
